# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 838)
        MainWindow.setToolTipDuration(-1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textedit_logs = TextEdit(self.centralwidget)
        self.textedit_logs.setGeometry(QtCore.QRect(30, 560, 1281, 211))
        self.textedit_logs.setObjectName("textedit_logs")
        self.search_zone = SearchLineEdit(self.centralwidget)
        self.search_zone.setGeometry(QtCore.QRect(70, 60, 311, 33))
        self.search_zone.setToolTip("")
        self.search_zone.setToolTipDuration(-2)
        self.search_zone.setWhatsThis("")
        self.search_zone.setAccessibleName("")
        self.search_zone.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.search_zone.setObjectName("search_zone")
        self.result_tableview = TableWidget(self.centralwidget)
        self.result_tableview.setGeometry(QtCore.QRect(540, 50, 791, 361))
        self.result_tableview.setObjectName("result_tableview")
        self.result_tableview.setColumnCount(0)
        self.result_tableview.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 130, 161, 105))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_company_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_company_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_company_name.setWordWrap(False)
        self.label_company_name.setObjectName("label_company_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_company_name)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_stock_code = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_stock_code.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stock_code.setWordWrap(False)
        self.label_stock_code.setObjectName("label_stock_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_stock_code)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_stock_price = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_stock_price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stock_price.setWordWrap(False)
        self.label_stock_price.setObjectName("label_stock_price")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_stock_price)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_final_score = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_final_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_final_score.setWordWrap(False)
        self.label_final_score.setObjectName("label_final_score")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_final_score)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_predict_result = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_predict_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_predict_result.setWordWrap(False)
        self.label_predict_result.setObjectName("label_predict_result")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_predict_result)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 290, 461, 116))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_search_cnt = Slider(self.horizontalLayoutWidget)
        self.slider_search_cnt.setMaximumSize(QtCore.QSize(230, 24))
        self.slider_search_cnt.setMaximum(10)
        self.slider_search_cnt.setSingleStep(10)
        self.slider_search_cnt.setPageStep(10)
        self.slider_search_cnt.setOrientation(QtCore.Qt.Horizontal)
        self.slider_search_cnt.setObjectName("slider_search_cnt")
        self.gridLayout.addWidget(self.slider_search_cnt, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_tamperature = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tamperature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tamperature.setWordWrap(False)
        self.label_tamperature.setObjectName("label_tamperature")
        self.gridLayout.addWidget(self.label_tamperature, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_date = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_date.setText("")
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setWordWrap(False)
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_search_cnt = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_search_cnt.setEnabled(True)
        self.label_search_cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_search_cnt.setWordWrap(False)
        self.label_search_cnt.setObjectName("label_search_cnt")
        self.gridLayout.addWidget(self.label_search_cnt, 0, 2, 1, 1)
        self.date_picker = ZhDatePicker(self.horizontalLayoutWidget)
        self.date_picker.setObjectName("date_picker")
        self.gridLayout.addWidget(self.date_picker, 1, 1, 1, 1)
        self.slider_temperature = Slider(self.horizontalLayoutWidget)
        self.slider_temperature.setMaximumSize(QtCore.QSize(230, 24))
        self.slider_temperature.setMaximum(100)
        self.slider_temperature.setOrientation(QtCore.Qt.Horizontal)
        self.slider_temperature.setObjectName("slider_temperature")
        self.gridLayout.addWidget(self.slider_temperature, 2, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(817, 460, 461, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_status = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_2.addWidget(self.label_status)
        self.progressbar_status = IndeterminateProgressBar(self.horizontalLayoutWidget_2)
        self.progressbar_status.setMaximumSize(QtCore.QSize(150, 4))
        self.progressbar_status.setObjectName("progressbar_status")
        self.horizontalLayout_2.addWidget(self.progressbar_status)
        self.request_line = LineEdit(self.centralwidget)
        self.request_line.setGeometry(QtCore.QRect(200, 460, 161, 33))
        self.request_line.setObjectName("request_line")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 470, 111, 16))
        self.label_9.setObjectName("label_9")
        self.button_predict = PrimaryPushButton(self.centralwidget)
        self.button_predict.setGeometry(QtCore.QRect(480, 460, 151, 33))
        self.button_predict.setObjectName("button_predict")
        self.label_stock_price_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_stock_price_3.setGeometry(QtCore.QRect(262, 392, 32, 16))
        self.label_stock_price_3.setText("")
        self.label_stock_price_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stock_price_3.setWordWrap(False)
        self.label_stock_price_3.setObjectName("label_stock_price_3")
        self.label_stock_price_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_stock_price_2.setGeometry(QtCore.QRect(91, 392, 32, 16))
        self.label_stock_price_2.setText("")
        self.label_stock_price_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stock_price_2.setWordWrap(False)
        self.label_stock_price_2.setObjectName("label_stock_price_2")
        self.button_save = PushButton(self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(650, 460, 151, 33))
        self.button_save.setObjectName("button_save")
        self.button_reset_all = PushButton(self.centralwidget)
        self.button_reset_all.setGeometry(QtCore.QRect(1060, 510, 100, 33))
        self.button_reset_all.setObjectName("button_reset_all")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_zone.setPlaceholderText(_translate("MainWindow", "公司名称/上市代码"))
        self.label_3.setText(_translate("MainWindow", "公司名称："))
        self.label_company_name.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "上市代码："))
        self.label_stock_code.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "股票价格："))
        self.label_stock_price.setText(_translate("MainWindow", "-"))
        self.label_10.setText(_translate("MainWindow", "最终评分："))
        self.label_final_score.setText(_translate("MainWindow", "-"))
        self.label_11.setText(_translate("MainWindow", "预测行情："))
        self.label_predict_result.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "最早日期："))
        self.label_tamperature.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Temperature："))
        self.label_5.setText(_translate("MainWindow", "搜索条数："))
        self.label_search_cnt.setText(_translate("MainWindow", "   -   "))
        self.label_8.setText(_translate("MainWindow", "状态："))
        self.label_status.setText(_translate("MainWindow", "-"))
        self.label_9.setText(_translate("MainWindow", "搜索公司名称："))
        self.button_predict.setText(_translate("MainWindow", "开始预测"))
        self.button_save.setText(_translate("MainWindow", "保存结果"))
        self.button_reset_all.setText(_translate("MainWindow", "异常重置"))
from qfluentwidgets import IndeterminateProgressBar, LineEdit, PrimaryPushButton, PushButton, SearchLineEdit, Slider, TableWidget, TextEdit, ZhDatePicker
